__name__ = "Auto-Approve-Bot"
__version__ = "2.0.0"
__license__ = " Apache License, Version 2.0"
__copyright__ = "Copyright (C) 2022-present Aero Developer <https://github.com/HarukiSama>"
__programer__ = "<a href=https://github.com/HarukiSama/Auto-Approve-bot>Mikoyo</a>"
__library__ = "<a href=https://github.com/pyrogram>Pyʀᴏɢʀᴀᴍ</a>"
__language__ = "<a href=https://www.python.org/>Pyᴛʜᴏɴ 3</a>"
__database__ = "<a href=https://cloud.mongodb.com/>Mᴏɴɢᴏ DB</a>"
__developer__ = "<a href=https://t.me/AeroBots_Tm>Aero Bot</a>"
__maindeveloper__ = "<a href=https://telegram.me/Mikoyo>Mikoyo</a>"
